### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dstan11** [fjxmlzn/GPUTaskScheduler#1]
Hi, I have ran pip install -e GPUTaskScheduler and it prints "Successfully intall". However, when I import gpu_task, it can not find the module. What should I do?

**Comment by fjxmlzn** [comment]
The library should be imported with gpu_task_scheduler, not gpu_task. You can find an example of how to use it here: https://github.com/fjxmlzn/PacGAN/blob/master/synthetic_data_experiments/2DGrid_GAN%26PacGAN/main.py

Let me know if you still have problems installing/using it.
