### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by AbbasiAYE** [fjxmlzn/GPUTaskScheduler#2]
Hi 

I used pip install . instead of pip install -e GPUTaskScheduler, because the editable one showed error 
(GANs_env4) 01108 [11:07] [.../workspace/GANs] -> pip install -e GPUTaskScheduler
ERROR: GPUTaskScheduler is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

do you think that is ok?

**Comment by fjxmlzn** [comment]
Just a double check if you have resolved the issue, as I saw that you have already closed it? The command "pip install -e GPUTaskScheduler" should be executed in the folder which contains the cloned GPUTaskScheduler repo. Let me know if you have any questions : )

**Comment by AbbasiAYE** [comment]
Thanks for the answer, It worked without -e earlier (because I downloaded a zipped version ;) )
Now with git clone it worked with -e

**Comment by fjxmlzn** [comment]
Great! Thanks!
